/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as ShopCategoryRouteImport } from './routes/shop.$category'
import { Route as ProductsHandleRouteImport } from './routes/products.$handle'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AdminPrintfulRouteImport } from './routes/admin.printful'
import { Route as ShopCategoryIndexRouteImport } from './routes/shop.$category.index'
import { Route as ShopCategorySubRouteImport } from './routes/shop.$category.$sub'
import { Route as ApiPublicPrintfulWebhookRouteImport } from './routes/api/public/printful-webhook'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionsRoute,
} as any)
const ShopCategoryRoute = ShopCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ShopRoute,
} as any)
const ProductsHandleRoute = ProductsHandleRouteImport.update({
  id: '/products/$handle',
  path: '/products/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CollectionsRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => CheckoutRoute,
} as any)
const AdminPrintfulRoute = AdminPrintfulRouteImport.update({
  id: '/admin/printful',
  path: '/admin/printful',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCategoryIndexRoute = ShopCategoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopCategoryRoute,
} as any)
const ShopCategorySubRoute = ShopCategorySubRouteImport.update({
  id: '/$sub',
  path: '/$sub',
  getParentRoute: () => ShopCategoryRoute,
} as any)
const ApiPublicPrintfulWebhookRoute =
  ApiPublicPrintfulWebhookRouteImport.update({
    id: '/api/public/printful-webhook',
    path: '/api/public/printful-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/collections': typeof CollectionsRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/printful': typeof AdminPrintfulRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/shop/$category': typeof ShopCategoryRouteWithChildren
  '/collections/': typeof CollectionsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/api/public/printful-webhook': typeof ApiPublicPrintfulWebhookRoute
  '/shop/$category/$sub': typeof ShopCategorySubRoute
  '/shop/$category/': typeof ShopCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/printful': typeof AdminPrintfulRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/collections': typeof CollectionsIndexRoute
  '/shop': typeof ShopIndexRoute
  '/api/public/printful-webhook': typeof ApiPublicPrintfulWebhookRoute
  '/shop/$category/$sub': typeof ShopCategorySubRoute
  '/shop/$category': typeof ShopCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/collections': typeof CollectionsRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/printful': typeof AdminPrintfulRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/shop/$category': typeof ShopCategoryRouteWithChildren
  '/collections/': typeof CollectionsIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/api/public/printful-webhook': typeof ApiPublicPrintfulWebhookRoute
  '/shop/$category/$sub': typeof ShopCategorySubRoute
  '/shop/$category/': typeof ShopCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/shop'
    | '/sitemap.xml'
    | '/admin/printful'
    | '/checkout/return'
    | '/collections/$slug'
    | '/orders/$id'
    | '/products/$handle'
    | '/shop/$category'
    | '/collections/'
    | '/shop/'
    | '/api/public/printful-webhook'
    | '/shop/$category/$sub'
    | '/shop/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/sitemap.xml'
    | '/admin/printful'
    | '/checkout/return'
    | '/collections/$slug'
    | '/orders/$id'
    | '/products/$handle'
    | '/collections'
    | '/shop'
    | '/api/public/printful-webhook'
    | '/shop/$category/$sub'
    | '/shop/$category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/shop'
    | '/sitemap.xml'
    | '/admin/printful'
    | '/checkout/return'
    | '/collections/$slug'
    | '/orders/$id'
    | '/products/$handle'
    | '/shop/$category'
    | '/collections/'
    | '/shop/'
    | '/api/public/printful-webhook'
    | '/shop/$category/$sub'
    | '/shop/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  CollectionsRoute: typeof CollectionsRouteWithChildren
  ShopRoute: typeof ShopRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminPrintfulRoute: typeof AdminPrintfulRoute
  OrdersIdRoute: typeof OrdersIdRoute
  ProductsHandleRoute: typeof ProductsHandleRoute
  ApiPublicPrintfulWebhookRoute: typeof ApiPublicPrintfulWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/collections/': {
      id: '/collections/'
      path: '/'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/shop/$category': {
      id: '/shop/$category'
      path: '/$category'
      fullPath: '/shop/$category'
      preLoaderRoute: typeof ShopCategoryRouteImport
      parentRoute: typeof ShopRoute
    }
    '/products/$handle': {
      id: '/products/$handle'
      path: '/products/$handle'
      fullPath: '/products/$handle'
      preLoaderRoute: typeof ProductsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/admin/printful': {
      id: '/admin/printful'
      path: '/admin/printful'
      fullPath: '/admin/printful'
      preLoaderRoute: typeof AdminPrintfulRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$category/': {
      id: '/shop/$category/'
      path: '/'
      fullPath: '/shop/$category/'
      preLoaderRoute: typeof ShopCategoryIndexRouteImport
      parentRoute: typeof ShopCategoryRoute
    }
    '/shop/$category/$sub': {
      id: '/shop/$category/$sub'
      path: '/$sub'
      fullPath: '/shop/$category/$sub'
      preLoaderRoute: typeof ShopCategorySubRouteImport
      parentRoute: typeof ShopCategoryRoute
    }
    '/api/public/printful-webhook': {
      id: '/api/public/printful-webhook'
      path: '/api/public/printful-webhook'
      fullPath: '/api/public/printful-webhook'
      preLoaderRoute: typeof ApiPublicPrintfulWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutReturnRoute: typeof CheckoutReturnRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutReturnRoute: CheckoutReturnRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface CollectionsRouteChildren {
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsSlugRoute: CollectionsSlugRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

interface ShopCategoryRouteChildren {
  ShopCategorySubRoute: typeof ShopCategorySubRoute
  ShopCategoryIndexRoute: typeof ShopCategoryIndexRoute
}

const ShopCategoryRouteChildren: ShopCategoryRouteChildren = {
  ShopCategorySubRoute: ShopCategorySubRoute,
  ShopCategoryIndexRoute: ShopCategoryIndexRoute,
}

const ShopCategoryRouteWithChildren = ShopCategoryRoute._addFileChildren(
  ShopCategoryRouteChildren,
)

interface ShopRouteChildren {
  ShopCategoryRoute: typeof ShopCategoryRouteWithChildren
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopCategoryRoute: ShopCategoryRouteWithChildren,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  CollectionsRoute: CollectionsRouteWithChildren,
  ShopRoute: ShopRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminPrintfulRoute: AdminPrintfulRoute,
  OrdersIdRoute: OrdersIdRoute,
  ProductsHandleRoute: ProductsHandleRoute,
  ApiPublicPrintfulWebhookRoute: ApiPublicPrintfulWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
