/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as ProductsHandleRouteImport } from './routes/products.$handle'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as AdminPrintfulRouteImport } from './routes/admin.printful'
import { Route as ApiPublicPrintfulWebhookRouteImport } from './routes/api/public/printful-webhook'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectionsRoute,
} as any)
const ProductsHandleRoute = ProductsHandleRouteImport.update({
  id: '/products/$handle',
  path: '/products/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CollectionsRoute,
} as any)
const AdminPrintfulRoute = AdminPrintfulRouteImport.update({
  id: '/admin/printful',
  path: '/admin/printful',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPrintfulWebhookRoute =
  ApiPublicPrintfulWebhookRouteImport.update({
    id: '/api/public/printful-webhook',
    path: '/api/public/printful-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/shop': typeof ShopRoute
  '/admin/printful': typeof AdminPrintfulRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/collections/': typeof CollectionsIndexRoute
  '/api/public/printful-webhook': typeof ApiPublicPrintfulWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/shop': typeof ShopRoute
  '/admin/printful': typeof AdminPrintfulRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/collections': typeof CollectionsIndexRoute
  '/api/public/printful-webhook': typeof ApiPublicPrintfulWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/shop': typeof ShopRoute
  '/admin/printful': typeof AdminPrintfulRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$handle': typeof ProductsHandleRoute
  '/collections/': typeof CollectionsIndexRoute
  '/api/public/printful-webhook': typeof ApiPublicPrintfulWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/shop'
    | '/admin/printful'
    | '/collections/$slug'
    | '/orders/$id'
    | '/products/$handle'
    | '/collections/'
    | '/api/public/printful-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/shop'
    | '/admin/printful'
    | '/collections/$slug'
    | '/orders/$id'
    | '/products/$handle'
    | '/collections'
    | '/api/public/printful-webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/shop'
    | '/admin/printful'
    | '/collections/$slug'
    | '/orders/$id'
    | '/products/$handle'
    | '/collections/'
    | '/api/public/printful-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CollectionsRoute: typeof CollectionsRouteWithChildren
  ShopRoute: typeof ShopRoute
  AdminPrintfulRoute: typeof AdminPrintfulRoute
  OrdersIdRoute: typeof OrdersIdRoute
  ProductsHandleRoute: typeof ProductsHandleRoute
  ApiPublicPrintfulWebhookRoute: typeof ApiPublicPrintfulWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/products/$handle': {
      id: '/products/$handle'
      path: '/products/$handle'
      fullPath: '/products/$handle'
      preLoaderRoute: typeof ProductsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/admin/printful': {
      id: '/admin/printful'
      path: '/admin/printful'
      fullPath: '/admin/printful'
      preLoaderRoute: typeof AdminPrintfulRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/printful-webhook': {
      id: '/api/public/printful-webhook'
      path: '/api/public/printful-webhook'
      fullPath: '/api/public/printful-webhook'
      preLoaderRoute: typeof ApiPublicPrintfulWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CollectionsRouteChildren {
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsSlugRoute: CollectionsSlugRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CollectionsRoute: CollectionsRouteWithChildren,
  ShopRoute: ShopRoute,
  AdminPrintfulRoute: AdminPrintfulRoute,
  OrdersIdRoute: OrdersIdRoute,
  ProductsHandleRoute: ProductsHandleRoute,
  ApiPublicPrintfulWebhookRoute: ApiPublicPrintfulWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
